version: 0.5.{build}
image: Visual Studio 2017

platform: x64

environment:
  global:
    PLATFORMTOOLSET: "v140"
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
# For now, maybe we disable 32 bit build-testing as it's unlikely for our users
#  - CMAKE_GENERATOR: "Visual Studio 15 2017"
#    QT5: C:\Qt\5.10.1\msvc2015
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    QT5: C:\Qt\5.12.6\msvc2017_64
    VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
    
branches:
  only:
  - master
  - develop

# preserve "3rd_party" directory in the root of build folder but will reset it if 3rd_party CMakeLists.txt is modified
cache:
  - 3rd_party -> **3rd_party\CMakeLists.txt

configuration: Release
shallow_clone: true
clone_depth: 5
matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

before_build:
- if exist "%QT5%" set Path=%QT5%\bin;%Path%
- md build
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"
- call "%VCVARS%"
- lib /def:Projects\CoX\Clients\patch_tools\CityOfX.def /OUT:Projects/CoX/Clients/patch_tools/CityOfX.lib
build_script:
- if "%APPVEYOR_REPO_TAG%"=="true" (set CONFIGURATION=RelWithDebInfo) else (set CONFIGURATION=Debug)
- cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

#after_build:
#- cmake --build build --config "%CONFIGURATION%" --target check -- %MSBUILD_FLAGS%
#- cmake --build build --config "%CONFIGURATION%" --target package -- %MSBUILD_FLAGS%
